#!/usr/bin/env python3

# File: pyproject-forge/pyproject_forge/generator.py
# Author: Hadi Cahyadi <cumulus13@gmail.com>
# Date: 2026-09-02 11:35:32
# Description: 
# License: MIT

"""Turns a PackageCandidate into a ready console-script package:
ensures __init__.py exists, ensures __main__.py exists with a resolvable
main()/usage() entry point, and reports what it did (or refused to do).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from .detector import find_entry_candidates, rank_candidates
from .exceptions import AmbiguousEntryPointError, NoEntryPointError
from .header_parser import detect_shebang, parse_header
from .scanner import PackageCandidate
from .utils import to_module_name

STUB_TEMPLATE = '''{shebang_line}"""Auto-generated console entry point for the "{name}" package.

pyproject-forge could not find an existing main()/cli()/run() function in
this folder, so it created this stub. Replace the body of main() with the
real behavior, or move your real entry function here and re-run the scan.
"""

import argparse
import sys


def usage() -> None:
    """Print basic usage information for this tool."""
    print(f"Usage: {{sys.argv[0]}} [options]")
    print("This is an auto-generated stub. Implement main() in __main__.py.")


def main(argv: list[str] | None = None) -> int:
    """Entry point invoked by the '{console_name}' console script."""
    parser = argparse.ArgumentParser(
        prog="{console_name}",
        description="TODO: describe what this tool does.",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="enable verbose output"
    )
    args = parser.parse_args(argv)

    if args.verbose:
        print("Verbose mode enabled.")

    usage()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

DELEGATE_TEMPLATE = '''{shebang_line}"""Console entry point for the "{name}" package.

Auto-generated by pyproject-forge: delegates to the existing
{source_module}.{func_name}() found in this package.
"""

from .{source_module} import {func_name} as main

if __name__ == "__main__":
    raise SystemExit(main())
'''

SELF_GUARD_SNIPPET = "\n\nif __name__ == \"__main__\":\n    raise SystemExit(main())\n"


class Action(str, Enum):
    UNCHANGED = "unchanged"
    ADDED_GUARD = "added_guard"
    CREATED_INIT = "created_init"
    CREATED_MAIN_DELEGATE = "created_main_delegate"
    CREATED_MAIN_STUB = "created_main_stub"
    SKIPPED_AMBIGUOUS = "skipped_ambiguous"
    SKIPPED_NO_ENTRY = "skipped_no_entry"
    SKIPPED_INVALID_NAME = "skipped_invalid_name"
    RENAMED_DIR = "renamed_dir"


@dataclass
class PackageResult:
    candidate: PackageCandidate
    module_name: str               # leaf module name only (for docstrings)
    dotted_module_name: str        # full dotted path, e.g. "toolA.sub"
    console_name: str
    entry_target: str | None       # dotted "pkg.__main__:func" for [project.scripts]
    actions: list[Action]
    detail: str = ""
    warnings: list[str] = None     # non-fatal notices, e.g. a '# File:' mismatch

    def __post_init__(self):
        if self.warnings is None:
            self.warnings = []

    @property
    def rel_path_posix(self) -> str:
        return self.candidate.rel_path.as_posix()


def _resolve_existing_main_entry(main_file: Path) -> tuple[str, bool] | None:
    """If __main__.py already has a top-level main()/usage()-style function,
    return (func_name, has_name_main_guard). Otherwise None.
    """
    candidates = rank_candidates(find_entry_candidates(main_file))
    if not candidates:
        return None
    best = candidates[0]
    source = main_file.read_text(encoding="utf-8")
    has_guard = '__name__ == "__main__"' in source or "__name__ == '__main__'" in source
    return best.func_name, has_guard


def _resolve_shebang(
    py_files: list[Path],
    forced_shebang: str | None,
    disable_shebang: bool,
    project_shebang: str | None,
) -> str | None:
    """Explicit --shebang wins, --no-shebang always wins over detection,
    otherwise use whatever this folder's own files already declare, and
    only fall back to a project-wide convention if this folder has none
    of its own. Never invents a shebang for a project that uses none.
    """
    if disable_shebang:
        return None
    if forced_shebang:
        return forced_shebang
    return detect_shebang(py_files, default=None) or project_shebang


def _make_executable_if_shebanged(path: Path, shebang: str | None) -> None:
    if not shebang:
        return
    try:
        path.chmod(path.stat().st_mode | 0o111)
    except OSError:
        pass  # best-effort only (e.g. unsupported on some filesystems)


def process_candidate(
    candidate: PackageCandidate,
    console_name: str,
    root: Path,
    allow_stub: bool = True,
    force: bool = False,
    auto_rename: bool = False,
    dry_run: bool = False,
    forced_shebang: str | None = None,
    disable_shebang: bool = False,
    project_shebang: str | None = None,
) -> PackageResult:
    actions: list[Action] = []
    warnings: list[str] = []
    module_name = to_module_name(candidate.name)

    # The dotted entry point ("dotted_module_name.__main__:func") only
    # resolves at import time if the folder on disk is actually named
    # `module_name`. We never silently pretend a sanitized name will
    # work — either rename the folder for real (only with explicit
    # opt-in) or flag it and skip.
    if module_name != candidate.name:
        if auto_rename:
            new_path = candidate.path.parent / module_name
            if new_path.exists():
                actions.append(Action.SKIPPED_INVALID_NAME)
                return PackageResult(
                    candidate, module_name, module_name, console_name, entry_target=None,
                    actions=actions,
                    detail=(
                        f"Folder name {candidate.name!r} is not a valid Python "
                        f"identifier and the auto-rename target {new_path} "
                        f"already exists. Rename manually."
                    ),
                )
            if not dry_run:
                candidate.path.rename(new_path)
                candidate.path = new_path
            actions.append(Action.RENAMED_DIR)
        else:
            actions.append(Action.SKIPPED_INVALID_NAME)
            return PackageResult(
                candidate, module_name, module_name, console_name, entry_target=None,
                actions=actions,
                detail=(
                    f"Folder name {candidate.name!r} is not a valid Python "
                    f"module name (would need to be {module_name!r}). "
                    f"Rename the folder or rerun with --auto-rename."
                ),
            )

    # Full dotted path from the ancestor chain of *selected* packages.
    # Empty parent_module_parts (the common, non-nested case) means
    # dotted_module_name == module_name, same as before.
    dotted_module_name = ".".join((*candidate.parent_module_parts, module_name))

    init_file = candidate.path / "__init__.py"
    main_file = candidate.path / "__main__.py"

    if not init_file.exists():
        if not dry_run:
            init_file.write_text(
                f'"""Package: {dotted_module_name}. Auto-created by pyproject-forge."""\n',
                encoding="utf-8",
            )
        actions.append(Action.CREATED_INIT)

    # Case 1: __main__.py already exists.
    if main_file.exists():
        resolved = _resolve_existing_main_entry(main_file)
        if resolved is None:
            if not allow_stub:
                raise NoEntryPointError(str(candidate.path))
            # __main__.py exists but has no recognizable entry function and
            # we are not allowed to silently rewrite user content.
            actions.append(Action.SKIPPED_NO_ENTRY)
            return PackageResult(
                candidate, module_name, dotted_module_name, console_name, entry_target=None,
                actions=actions, warnings=warnings,
                detail=(
                    f"{main_file} exists but defines no main/cli/run/app/usage "
                    f"function. Add one manually, mark it with "
                    f"'# pyproject-forge: entry', or rerun with --force-stub."
                ),
            )
        func_name, has_guard = resolved
        if not has_guard:
            if not dry_run:
                with main_file.open("a", encoding="utf-8") as f:
                    f.write(SELF_GUARD_SNIPPET.replace("main()", f"{func_name}()"))
            actions.append(Action.ADDED_GUARD)
        else:
            actions.append(Action.UNCHANGED)
        entry_target = f"{dotted_module_name}.__main__:{func_name}"
        return PackageResult(
            candidate, module_name, dotted_module_name, console_name, entry_target, actions,
            warnings=warnings,
        )

    # Case 2: no __main__.py yet — look for a candidate elsewhere in the
    # folder (e.g. app.py defining main()). Always a *sibling* file in
    # this same folder (the scanner only collects direct children), so
    # the generated import is always a single-dot relative import
    # regardless of how deeply this package itself is nested.
    all_candidates = []
    for py_file in candidate.py_files:
        if py_file.name == "__init__.py":
            continue
        for c in find_entry_candidates(py_file):
            all_candidates.append(c)

    ranked = rank_candidates(all_candidates)
    if ranked:
        top_rank_key = (
            ranked[0].is_marked,
            ranked[0].func_name,
        )
        tied = [
            c for c in ranked
            if (c.is_marked, c.func_name) == top_rank_key
            and c.module_file != ranked[0].module_file
        ]
        if tied and not ranked[0].is_marked:
            raise AmbiguousEntryPointError(
                str(candidate.path),
                sorted({c.module_file.name for c in ranked}),
            )
        best = ranked[0]
        source_module = to_module_name(best.module_file.stem)

        # Cross-check the source file's own '# File:' header comment
        # (if it declares one) against where it actually lives — a
        # stale header is a real signal something got moved/renamed
        # and is worth surfacing, never silently ignored.
        source_header = parse_header(best.module_file)
        if source_header.file_field:
            declared = source_header.file_field.replace("\\", "/").lstrip("./")
            actual = best.module_file.relative_to(root).as_posix()
            if declared != actual:
                warnings.append(
                    f"{best.module_file}: header says 'File: {source_header.file_field}' "
                    f"but the file is actually at '{actual}'"
                )

        shebang = _resolve_shebang(
            candidate.py_files, forced_shebang, disable_shebang, project_shebang
        )
        if not dry_run:
            main_file.write_text(
                DELEGATE_TEMPLATE.format(
                    shebang_line=f"{shebang}\n" if shebang else "",
                    name=candidate.name,
                    source_module=source_module,
                    func_name=best.func_name,
                ),
                encoding="utf-8",
            )
            _make_executable_if_shebanged(main_file, shebang)
        actions.append(Action.CREATED_MAIN_DELEGATE)
        entry_target = f"{dotted_module_name}.__main__:main"
        return PackageResult(
            candidate, module_name, dotted_module_name, console_name, entry_target,
            actions, warnings=warnings,
        )

    # Case 3: nothing found anywhere in the folder.
    if not allow_stub:
        raise NoEntryPointError(str(candidate.path))
    shebang = _resolve_shebang(
        candidate.py_files, forced_shebang, disable_shebang, project_shebang
    )
    if not dry_run:
        main_file.write_text(
            STUB_TEMPLATE.format(
                shebang_line=f"{shebang}\n" if shebang else "",
                name=candidate.name,
                console_name=console_name,
            ),
            encoding="utf-8",
        )
        _make_executable_if_shebanged(main_file, shebang)
    actions.append(Action.CREATED_MAIN_STUB)
    entry_target = f"{dotted_module_name}.__main__:main"
    return PackageResult(
        candidate, module_name, dotted_module_name, console_name, entry_target,
        actions, warnings=warnings,
    )
